"""Add avatar url and back ground url

Revision ID: 2e8661ad2509
Revises: ed6e7d448230
Create Date: 2025-07-18 04:24:12.733516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e8661ad2509'
down_revision: Union[str, Sequence[str], None] = 'ed6e7d448230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('notification', 'type',
    #            existing_type=sa.VARCHAR(length=10),
    #            type_=sa.Enum('Comment', 'Emote', name='notitype'),
    #            existing_nullable=False)
    op.add_column('user', sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('background', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'background')
    op.drop_column('user', 'avatar')
    op.alter_column('notification', 'type',
               existing_type=sa.Enum('Comment', 'Emote', name='notitype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
