"""Change emote table

Revision ID: 6a4e7b0f11f1
Revises: 2e8661ad2509
Create Date: 2025-07-18 23:22:05.422739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a4e7b0f11f1'
down_revision: Union[str, Sequence[str], None] = '2e8661ad2509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Tạo bảng tạm với kiểu dữ liệu mới
    op.create_table(
        'emote_tmp',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('post_id', sa.Integer, nullable=False),
        sa.Column('user_id', sa.Integer, nullable=False),
        sa.Column('type', sa.String, nullable=False),
        sa.Column('create_date', sa.DateTime, nullable=False),  # sửa kiểu tại đây
        # thêm các column khác nếu cần
    )

    # copy data từ bảng cũ sang bảng mới
    op.execute('INSERT INTO emote_tmp (id, post_id, user_id, type, create_date) SELECT id, post_id, user_id, type, create_date FROM emote')

    # xoá bảng cũ
    op.drop_table('emote')

    # rename bảng tạm thành bảng chính
    op.rename_table('emote_tmp', 'emote')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emote', 'create_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
