"""Add noti table

Revision ID: ca53f1e6b4c8
Revises: a521c4f2f0a0
Create Date: 2025-07-01 22:01:48.852455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca53f1e6b4c8'
down_revision: Union[str, Sequence[str], None] = 'a521c4f2f0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.text("0")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_read')
    # ### end Alembic commands ###
