"""add friendship foreign keys

Revision ID: ed6e7d448230
Revises: ca53f1e6b4c8
Create Date: 2025-07-10 23:10:19.556671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed6e7d448230'
down_revision: Union[str, Sequence[str], None] = 'ca53f1e6b4c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Kiểm tra nếu bảng friendship chưa tồn tại mới tạo
    if 'friendship' not in inspector.get_table_names():
        op.create_table('friendship',
            sa.Column('sender_id', sa.Integer(), nullable=False),
            sa.Column('receiver_id', sa.Integer(), nullable=False),
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='friendshipstatus'), nullable=False),
            sa.Column('create_date', sa.Date(), nullable=False),
            sa.ForeignKeyConstraint(['receiver_id'], ['user.id']),
            sa.ForeignKeyConstraint(['sender_id'], ['user.id']),
            sa.PrimaryKeyConstraint('id')
        )

    # Kiểm tra nếu bảng friend tồn tại mới xóa
    if 'friend' in inspector.get_table_names():
        op.drop_table('friend')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'type',
               existing_type=sa.Enum('Comment', 'Emote', name='notitype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.create_table('friend',
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('create_date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('friendship')
    # ### end Alembic commands ###
